
server:
  error:
    include-stacktrace: on_param

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: 12345

  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update
    open-in-view: false

logging:
  level:
    org:
      hibernate:
        SQL: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: "*"
info:
  app: Spring Boot Essentials
  github: https://github.com/Rayllanderson
